
app: idorg
deployment: satellite
environment: staging
active_profiles: authenabled

actuator_auth:
  role: ~
  issuer_uri: ~


ingress: #This assumes google cloud ingress
  enabled: true
  static_ip_name: idorg-satellite
  allow_http: true
  pre_shared_cert: 'cert-iorg-sat-prod-metadata,cert-iorg-sat-prod-resolver,cert-iorg-sat-prod-sparql,cert-iorg-sat-prod-web,cert-iorg-sat-prod-web-main2'

redis:
  component: redis
  tier: backend
  image: "redis:7.4-alpine"
  requests:
    memory: 1280Mi
    cpu: 150m

sparql:
  component: sparql
  tier: api
  image: "identifiersorg/sparql-identifiers:2.1.3"
  replicas: 1
  requests:
    memory: 360Mi
    cpu: 100m
  port: 8080

resource_recommender:
  component: resource-recommender
  tier: api
  image: "identifiersorg/cloud-ws-resource-recommender:2.0.1"
  replicas: 2
  port: 8083
  requests:
    memory: 360Mi
    cpu: 150m

link_checker:
  component: link-checker
  tier: api
  image: "identifiersorg/cloud-ws-link-checker:2.1.8"
  replicas: 1
  requests:
    memory: 440Mi
    cpu: 100m
  limits:
    cpu: 800m
  port: 8084

metadata:
  component: metadata
  tier: api
  image: "identifiersorg/cloud-ws-metadata:2.0.0"
  replicas: 1
  port: 8082
  requests:
    cpu: 100m
    memory: 640Mi

resolver:
  component: resolver
  tier: api
  image: "identifiersorg/cloud-ws-resolver:3.1.0"
  replicas: 3
  port: 8080
  url: "https://resolver.api.identifiers.org"
  cors_origins: "*"
  requests:
    memory: 360Mi
    cpu: 100m

matomo:
  enabled: false
  baseUrl: "https://matomo.identifiers.org/matomo.php"

frontend:
  component: web-satellite
  tier: frontend
  image: "identifiersorg/cloud-satellite-web-spa:2.1.0"
  replicas: 3
  cors_origins: "*"
  port: 9090
  requests:
    memory: 420Mi
    cpu: 100m

registry:
  url: "https://registry.identifiers.org"
  api_url: "https://registry.api.identifiers.org"
  registration_url: "https://registry.identifiers.org/prefixregistrationrequest"
  dataset_url: "https://registry.api.identifiers.org/resolutionApi/getResolverDataset"

nodeAffinityRequirements:
  - label: idorg-node-reliability
    value: stable
  - label: idorg-deployment
    value: satellite
