
app: idorg
deployment: satellite
environment: staging

ingress: #This assumes google cloud ingress
  static_ip_name: idorg-satellite
  allow_http: true
  pre_shared_cert: 'cert-iorg-sat-prod-metadata,cert-iorg-sat-prod-resolver,cert-iorg-sat-prod-sparql,cert-iorg-sat-prod-web,cert-iorg-sat-prod-web-main2'

redis:
  image: "redis:4.0.8-alpine"
  requests:
    memory: 1280Mi
    cpu: 150m

sparql:
  image: "jerven/sparql-identifiers:1.3"
  replicas: 1
  requests:
    memory: 360Mi
    cpu: 100m
  port: 8080

resource_recommender:
  image: "identifiersorg/cloud-ws-resource-recommender:1.3.2"
  replicas: 2
  port: 8083
  requests:
    memory: 360Mi
    cpu: 150m

link_checker:
  image: "identifiersorg/cloud-ws-link-checker:1.3.2"
  replicas: 1
  requests:
    memory: 440Mi
    cpu: 100m
  port: 8084

metadata:
  image: "identifiersorg/cloud-ws-metadata:1.4.2"
  replicas: 1
  port: 8082
  requests:
    memory: 640Mi

resolver:
  image: "identifiersorg/cloud-ws-resolver:2.2.6"
  replicas: 2
  port: 8080
  url: "https://resolver.api.identifiers.org"
  cors_origins: "http://cloud.identifiers.org,https://cloud.identifiers.org,http://cloud.aws.identifiers.org,https://cloud.aws.identifiers.org,http://cloud.gcloud.identifiers.org,https://cloud.gcloud.identifiers.org,http://identifiers.org,https://identifiers.org"
  requests:
    memory: 360Mi
    cpu: 100m

frontend:
  image: "identifiersorg/cloud-satellite-web-spa:0.5.7"
  replicas: 2
  cors_origins: "http://identifiers.org,https://identifiers.org,http://cloud.identifiers.org,https://cloud.identifiers.org"
  port: 9090
  requests:
    memory: 420Mi
    cpu: 100m

registry:
  url: "https://registry.identifiers.org"
  api_url: "https://registry.api.identifiers.org"
  registration_url: "https://registry.identifiers.org/prefixregistrationrequest"
  dataset_url: "https://registry.api.identifiers.org/resolutionApi/getResolverDataset"

nodeAffinityRequirements:
  - label: iorg-node-reliability
    value: stable