# This file defines an Horizontal Pod Autoscaler for the target deployment
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: metadata
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: metadata
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 65