---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparql
  labels:
    {{- (include "common_labels" .) | indent 4 }}
    component: sparql
    tier: api
spec:
  selector:
    matchLabels:
      tier: api
      component: sparql
      {{- (include "common_labels" .) | indent 6 }}
  replicas: {{ .Values.sparql.replicas }}
  template:
    metadata:
      labels:
        tier: api
        component: sparql
        {{- (include "common_labels" .) | indent 8 }}
    spec:
      {{- (include "affinity_requirements" .) | indent 6 }}
      containers:
        - name: sparql-identifiers
          image: {{ .Values.sparql.image }}
          imagePullPolicy: Always
          resources:
            requests:
              memory: {{ .Values.sparql.requests.memory }}
              cpu: {{ .Values.sparql.requests.cpu }}
          ports:
            - containerPort: {{ .Values.sparql.port }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":false}'
  name: sparql
  labels:
    tier: api
    component: sparql
    {{- (include "common_labels" .) | indent 4 }}
spec:
  ports:
    - port: {{ .Values.sparql.port }}
  selector:
    tier: api
    component: sparql
    {{- (include "common_labels" .) | indent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: nodeport-sparql
  labels:
    tier: api
    component: sparql
    {{- (include "common_labels" .) | indent 4 }}
spec:
  ports:
    - port: {{ .Values.sparql.port }}
  selector:
    tier: api
    component: sparql
    {{- (include "common_labels" .) | indent 4 }}
  type: NodePort
---
