# Identifiers.org satellite platform ingress controller
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: satellite-deployment
  labels:
    environment: production
    tier: api
    app: satellite-deployment
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: idorg-satellite
    ingress.gcp.kubernetes.io/pre-shared-cert: 'cert-iorg-sat-prod-metadata,cert-iorg-sat-prod-resolver,cert-iorg-sat-prod-sparql,cert-iorg-sat-prod-web,cert-iorg-sat-prod-web-main2'
    # ingress.gcp.kubernetes.io/pre-shared-cert: 'cert-iorg-sat-prod-resolver,cert-iorg-sat-prod-metadata,cert-iorg-sat-prod-web,cert-iorg-sat-prod-web-main2,cert-iorg-sat-prod-sparql'
    kubernetes.io/ingress.allow-http: "true"
spec:
  rules:
    # Resolver rules
    - host: resolver.api.identifiers.org
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: nodeport-resolver
                port:
                  number: 8080
    # Sparql rules
    - host: sparql.api.identifiers.org
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: nodeport-sparql
                port:
                  number: 8080
    # Metadata Service rules
    - host: metadata.api.identifiers.org
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: nodeport-metadata
                port:
                  number: 8082
    # Web Frontend rules
    - host: cloud.identifiers.org
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: nodeport-web-satellite
                port:
                  number: 80
    - host: identifiers.org
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: nodeport-web-satellite
                port:
                  number: 80
