---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.component }}
  labels:
    {{- (include "common_labels" .) | indent 4 }}
    component: {{ .Values.frontend.component }}
    tier: {{ .Values.frontend.tier }}
spec:
  selector:
    matchLabels:
      tier: {{ .Values.frontend.tier }}
      component: {{ .Values.frontend.component }}
      {{- (include "common_labels" .) | indent 6 }}
  replicas: {{ .Values.frontend.replicas }}
  template:
    metadata:
      labels:
        tier: {{ .Values.frontend.tier }}
        component: {{ .Values.frontend.component }}
        {{- (include "common_labels" .) | indent 8 }}
    spec:
      affinity:
        {{- (include "node_affinity_requirements" .) | indent 8 }}
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 70
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    {{- (include "common_label_match_expressions" .) | indent 20}}
                    - key: tier
                      operator: In
                      values:
                        - {{ .Values.resolver.tier }}
                    - key: component
                      operator: In
                      values:
                        - {{ .Values.resolver.component }}
                topologyKey: "kubernetes.io/hostname"
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    {{- (include "common_label_match_expressions" .) | indent 20}}
                    - key: tier
                      operator: In
                      values:
                        - {{ .Values.frontend.tier }}
                    - key: component
                      operator: In
                      values:
                        - {{ .Values.frontend.component }}
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: cloud-web-frontend
          image: {{ .Values.frontend.image }}
          imagePullPolicy: Always
          resources:
            requests:
              memory: {{ .Values.frontend.requests.memory }}
              cpu: {{ .Values.frontend.requests.cpu }}
          env:
            - name: SATELLITE_WEB_SPA_CONFIG_WS_RESOLVER_HOST
              value: "resolver"
            - name: SATELLITE_WEB_SPA_CONFIG_WS_RESOLVER_PORT
              value: {{ .Values.resolver.port | quote }}
            - name: SATELLITE_WEB_SPA_CONFIG_WS_RESOLVER_SCHEMA
              value: "http"
            - name: SATELLITE_WEB_SPA_CONFIG_WS_RESOLVER_URL
              value: {{ .Values.resolver.url | quote }}
            - name: SATELLITE_WEB_SPA_CONFIG_WS_HQ_REGISTRY_URL
              value: {{ .Values.registry.api_url | quote }}
            - name: SATELLITE_WEB_SPA_CONFIG_WS_API_VERSION
              value: "1.0"
            - name: SATELLITE_WEB_SPA_CONFIG_WEB_HQ_REGISTRY_URL
              value: {{ .Values.registry.url | quote }}
            - name: SATELLITE_WEB_SPA_CONFIG_WEB_HQ_REGISTRY_PREFIX_REGISTRATION_FORM_URL
              value: {{ .Values.registry.registration_url | quote }}
            - name: SATELLITE_WEB_SPA_CONFIG_FLAG_SHOW_SEARCH_SUGGESTIONS
              value: "true"
            - name: SATELLITE_WEB_SPA_CONFIG_CORS_ORIGIN
              value: {{ .Values.frontend.cors_origins | quote }}
            - name: WEB_SATELLITE_WS_JVM_MEMORY_MAX
              value: {{ .Values.frontend.requests.memory | lower | trimSuffix "i" | quote }}
            - name: MATOMO_ENABLED
              value: {{ .Values.matomo.enabled | quote }}
            - name: MATOMO_BASE_URL
              value: {{ .Values.matomo.baseUrl | quote }}
            - name: MATOMO_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: matomo-credentials
                  key: auth_token
          ports:
            - containerPort: {{ .Values.frontend.port }}
          readinessProbe:
            httpGet:
              path: /healthApi/readiness_check
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthApi/liveness_check
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: nodeport-{{ .Values.frontend.component }}
  labels:
    tier: {{ .Values.frontend.tier }}
    component: {{ .Values.frontend.component }}
    {{- (include "common_labels" .) | indent 4 }}
spec:
  ports:
    - port: 80
      targetPort: {{ .Values.frontend.port }}
  selector:
    tier: {{ .Values.frontend.tier }}
    component: {{ .Values.frontend.component }}
    {{- (include "common_labels" .) | indent 4 }}
  type: NodePort
---