---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata
  labels:
    {{- (include "common_labels" .) | indent 4 }}
    component: metadata
    tier: api
spec:
  selector:
    matchLabels:
      tier: api
      component: metadata
      {{- (include "common_labels" .) | indent 6 }}
  replicas: {{ .Values.metadata.replicas }}
  template:
    metadata:
      labels:
        tier: api
        component: metadata
        {{- (include "common_labels" .) | indent 8 }}
    spec:
      {{- (include "affinity_requirements" .) | indent 6 }}
      containers:
        - name: cloud-ws-metadata
          image: {{ .Values.metadata.image }}
          imagePullPolicy: Always
          resources:
            requests:
              memory: {{ .Values.metadata.requests.memory }}
              cpu: {{ .Values.metadata.requests.cpu }}
          env:
            - name: WS_METADATA_CONFIG_RESOLVER_HOST
              value: "resolver"
            - name: WS_METADATA_CONFIG_RESOLVER_PORT
              value: {{ .Values.resolver.port | quote }}
            - name: WS_METADATA_JVM_MEMORY_MAX
              value: {{ .Values.metadata.requests.memory | lower | trimSuffix "i" | quote }}
            - name: WS_METADATA_CONFIG_REDIS_HOST
              value: "redis"
            - name: WS_METADATA_CONFIG_BACKEND_REQUIRED_ROLE
              value: {{ .Values.actuator_auth.role }}
            - name: WS_METADATA_CONFIG_BACKEND_SERVICE_JWT_ISSUERURI
              value: {{ .Values.actuator_auth.issuer_uri }}
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.active_profiles }}
          ports:
            - containerPort: {{ .Values.metadata.port }}
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.metadata.port }}
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 25
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.metadata.port }}
            initialDelaySeconds: 20
            periodSeconds: 30
            timeoutSeconds: 25
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":false}'
  name: metadata
  labels:
    tier: api
    component: metadata
    {{- (include "common_labels" .) | indent 4 }}
spec:
  ports:
    - port: {{ .Values.metadata.port }}
  selector:
    tier: api
    component: metadata
    {{- (include "common_labels" .) | indent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: nodeport-metadata
  labels:
    tier: api
    component: metadata
    {{- (include "common_labels" .) | indent 4 }}
spec:
  ports:
    - port: {{ .Values.metadata.port }}
  selector:
    tier: api
    component: metadata
    {{- (include "common_labels" .) | indent 4 }}
  type: NodePort
