---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.resolver.component }}
  labels:
    {{- (include "common_labels" .) | indent 4 }}
    component: {{ .Values.resolver.component }}
    tier: {{ .Values.resolver.tier }}
spec:
  selector:
    matchLabels:
      tier: {{ .Values.resolver.tier }}
      component: {{ .Values.resolver.component }}
      {{- (include "common_labels" .) | indent 6 }}
  replicas: {{ .Values.resolver.replicas }}
  template:
    metadata:
      labels:
        tier: {{ .Values.resolver.tier }}
        component: {{ .Values.resolver.component }}
        {{- (include "common_labels" .) | indent 8 }}
    spec:
      affinity:
        {{- (include "node_affinity_requirements" .) | indent 8 }}
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 70
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    {{- (include "common_label_match_expressions" .) | indent 20 }}
                    - key: tier
                      operator: In
                      values:
                        - {{ .Values.redis.tier }}
                    - key: component
                      operator: In
                      values:
                        - {{ .Values.redis.component }}
                topologyKey: "kubernetes.io/hostname"
            - weight: 20
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    {{- (include "common_label_match_expressions" .) | indent 20 }}
                    - key: tier
                      operator: In
                      values:
                        - {{ .Values.resource_recommender.tier }}
                    - key: component
                      operator: In
                      values:
                        - {{ .Values.resource_recommender.component }}
                topologyKey: "kubernetes.io/hostname"
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    {{- (include "common_label_match_expressions" .) | indent 20}}
                    - key: tier
                      operator: In
                      values:
                        - {{ .Values.resolver.tier }}
                    - key: component
                      operator: In
                      values:
                        - {{ .Values.resolver.component }}
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: cloud-ws-resolver
          image: {{ .Values.resolver.image }}
          imagePullPolicy: Always
          resources:
            requests:
              memory: {{ .Values.resolver.requests.memory }}
              cpu: {{ .Values.resolver.requests.cpu }}
          env:
            - name: WS_RESOLVER_CONFIG_REDIS_HOST
              value: "redis"
            - name: WS_RESOLVER_CONFIG_REDIS_PORT
              value: "6379"
            - name: WS_RESOLVER_CONFIG_RESOURCE_RECOMMENDER_HOST
              value: "resource-recommender"
            - name: WS_RESOLVER_CONFIG_RESOURCE_RECOMMENDER_PORT
              value: {{ .Values.resource_recommender.port | quote }}
            - name: WS_RESOLVER_CONFIG_REGISTRY_RESOLUTION_DATASET_ENDPOINT
              value: {{ .Values.registry.dataset_url | quote }}
            - name: WS_RESOLVER_CONFIG_APPLICATION_CORS_ORIGINS
              value: {{ .Values.resolver.cors_origins | quote }}
            - name: WS_RESOLVER_JVM_MEMORY_MAX
              value: {{ .Values.resolver.requests.memory | lower | trimSuffix "i" | quote }}
            - name: MATOMO_ENABLED
              value: {{ .Values.matomo.enabled | quote }}
            - name: MATOMO_BASE_URL
              value: {{ .Values.matomo.baseUrl | quote }}
            - name: MATOMO_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: matomo-credentials
                  key: auth_token
            - name: WS_RESOLVER_CONFIG_BACKEND_REQUIRED_ROLE
              value: {{ .Values.actuator_auth.role | default "" | quote }}
            - name: WS_RESOLVER_CONFIG_BACKEND_SERVICE_JWT_ISSUERURI
              value: {{ .Values.actuator_auth.issuer_uri | required "Set a authenticator provider!" | quote }}
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.active_profiles }}
          ports:
            - containerPort: {{ .Values.resolver.port }}
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.resolver.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.resolver.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":false}'
  name: {{ .Values.resolver.component }}
  labels:
    tier: {{ .Values.resolver.tier}}
    component: {{ .Values.resolver.component }}
    {{- (include "common_labels" .) | indent 4 }}
spec:
  ports:
    - port: {{ .Values.resolver.port }}
  selector:
    tier: {{ .Values.resolver.tier}}
    component: {{ .Values.resolver.component }}
    {{- (include "common_labels" .) | indent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: nodeport-{{ .Values.resolver.component }}
  labels:
    tier: {{ .Values.resolver.tier}}
    component: {{ .Values.resolver.component }}
    {{- (include "common_labels" .) | indent 4 }}
spec:
  ports:
    - port: {{ .Values.resolver.port }}
  selector:
    tier: {{ .Values.resolver.tier}}
    component: {{ .Values.resolver.component }}
    {{- (include "common_labels" .) | indent 4 }}
  type: NodePort
---